#Numpy Arrays

In [ ]:
import numpy as np

#python list
my_list = [1,2,3]
#print(my_list)

# pyhton list cast into numpy array
arr = np.array(my_list)
#print(arr)


# 2-d list
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
#print(mat)


# range alternative
#np.arange(0,10,2)
#print(arr1)

np.zeros(3)

In [4]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [11]:
#INdentity matrix 

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
#random numbers arrays

#gives uniformly distributed no. in a range
np.random.rand(5)

array([0.92883014, 0.98780899, 0.45984367, 0.38862388, 0.5431201 ])

In [13]:
np.random.rand(5,5)

array([[0.09752787, 0.01391183, 0.14800357, 0.25049358, 0.21668941],
       [0.43000132, 0.95714505, 0.54536295, 0.12521737, 0.55572559],
       [0.35122538, 0.23222134, 0.33185143, 0.19959817, 0.60654734],
       [0.24003678, 0.25768829, 0.32599163, 0.93833986, 0.05469597],
       [0.07171086, 0.45615921, 0.10669535, 0.81741702, 0.53732188]])

In [16]:
# sample from standard normal dist.

np.random.randn(3,3)

array([[ 0.06213263,  0.90019301,  0.20623199],
       [ 0.14365707,  0.81232922,  0.36461959],
       [-0.70285159,  0.10438355, -0.44890743]])

In [29]:
ranarr = np.random.randint(1,40,5)
ranarr

array([ 7,  9, 16,  9, 31])

In [21]:
arr = np.arange(25)

In [23]:
# reshape a array
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr.max()

31

In [31]:
ranarr.min()

7

In [33]:
#index location max value
ranarr.argmax()

4

In [37]:
arr.shape

(25,)

In [39]:
arr.dtype

dtype('int32')

# Numpy Indexing and Selection

In [40]:
arr1 = np.arange(0,11)

In [42]:
arr1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
#indexing
arr1[8]

8

In [47]:
#slicing
arr1[1:5]

array([1, 2, 3, 4])

In [48]:
arr1[5:]

array([ 5,  6,  7,  8,  9, 10])

In [49]:
slice_of_arr = arr1[0:6]

In [50]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [51]:
slice_of_arr[:]=99

In [52]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [54]:
arr1

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [56]:
# specificly  specify copy of array

arr_copy = arr1.copy()

In [57]:
arr1

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [58]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [59]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [60]:
arr1

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

2-d array indexing

In [61]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [62]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [65]:
arr_2d[0,2]

15